server:
  port: 8080

spring:
  application:
    name: spring-boot-framework-prod

logging:
  level:
    com.pkfare.tripscale: WARN
    org.springframework: WARN
    org.springframework.web: WARN
    org.springframework.boot: WARN
    org.hibernate: WARN
    org.apache: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/application-prod.log

# Production specific configurations
management:
  endpoints:
    web:
      exposure:
        include: health

# External service configurations for production
external:
  dify:
    base-url: ${DIFY_BASE_URL}
    api-key: ${DIFY_API_KEY}
    timeout-seconds: 30
    max-retries: 3
    retry-delay-ms: 1000
  
  memory:
    base-url: ${MEMORY_BASE_URL}
    api-key: ${MEMORY_API_KEY}
    timeout-seconds: 15
    max-retries: 3
    retry-delay-ms: 500
  
  trip-knowledge:
    base-url: ${TRIP_KNOWLEDGE_BASE_URL}
    api-key: ${TRIP_KNOWLEDGE_API_KEY}
    timeout-seconds: 20
    max-retries: 3
    retry-delay-ms: 1000