server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: spring-boot-framework

logging:
  level:
    com.pkfare.tripscale: INFO
    org.springframework: WARN
    org.springframework.web: INFO
    org.springframework.boot: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/application.log