server:
  port: 8080

spring:
  application:
    name: spring-boot-framework-dev

logging:
  level:
    com.pkfare.tripscale: DEBUG
    org.springframework: INFO
    org.springframework.web: DEBUG
    org.springframework.boot: INFO
    org.hibernate: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/application-dev.log

# Development specific configurations
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

# External service configurations for development
external:
  dify:
    base-url: http://localhost:8001
    api-key: dev-dify-api-key
    timeout-seconds: 30
    max-retries: 2
    retry-delay-ms: 500
  
  memory:
    base-url: http://localhost:8002
    api-key: dev-memory-api-key
    timeout-seconds: 15
    max-retries: 2
    retry-delay-ms: 300
  
  trip-knowledge:
    base-url: http://localhost:8003
    api-key: dev-trip-knowledge-api-key
    timeout-seconds: 20
    max-retries: 2
    retry-delay-ms: 500